# Generated by Django 4.2.4 on 2023-08-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
